---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Employees
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: EmployeeService
  annotations:
    revision.app/preferred-diagram-slug: hzWULbREwZhR
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: Employees
